version: "3.8"

services:

  blazegraph_dh:
    container_name: "blazegraph_dh_agent"
    image: docker.cmclinnovations.com/blazegraph:1.0.0-SNAPSHOT
    restart: unless-stopped
    ports:
      - "9999:8080"
    volumes:
      - blazegraph_dh_data:/blazegraph

  postgres_dh:
    container_name: "postgres_dh_agent"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    image: postgres:13.3
    restart: unless-stopped
    ports:
      - "9432:5432"
    volumes:
      - postgres_dh_data:/var/lib/postgresql/data

# you have to first instantiate the data to then use here the existing external volumes 
volumes:
  blazegraph_dh_data:
    external: true
    name: "blazegraph_dh_data"
  postgres_dh_data:
    external: true
    name: "postgres_dh_data"