version: '3.8'
services:
  stack-data-uploader:
    image: docker.cmclinnovations.com/stack-data-uploader:1.6.0
    configs:
      - postgis
      - geoserver
    secrets:
      - postgis_password
      - geoserver_password
    volumes:
      - ./inputs/data:/inputs/data
      - ./inputs/config:/inputs/config
