version: "3.8"

services:
  modssimpleagent:
    image: docker.cmclinnovations.com/modssimpleagent:0.4.0-dev-mods-agent-algorithm-settings-SNAPSHOT
    build: .
    container_name: modssimpleagent
    environment:
      DATA_DIR: /app/files
      CMCL_LICENSE_PATH: "/run/secrets/mods_agent_licence"
    ports:
      - "58085:58085"
      - "8000:8000"
    secrets:
      - mods_agent_licence
    volumes:
      - "./SavedSurrogates:/usr/local/mods-simple-agent/SavedSurrogates/"

# Secrets
secrets:
  mods_agent_licence:
    file: ./secrets/docker-agent-licence.lic
